import { test, expect } from "@playwright/test";
import { login, goToWizard, completeStepOne } from "../helpers/wizard";

test("wizard step 3: user fills website details", async ({ page }) => {
  await login(page);
  await goToWizard(page);
  await completeStepOne(page);

  // Step 2 → move to Step 3
  const projectsPage = page.getByRole("button", { name: /projects/i });

  if (await projectsPage.isVisible()) {
    await projectsPage.click();
  }

  await page.getByRole("button", { name: /next step/i }).click();

  // ✅ Step 3 visible
  await expect(
    page.getByRole("heading", { name: /website details/i }),
  ).toBeVisible();

  // Fill Website Name
  await page.getByLabel(/website name/i).fill("Test Website");

  // Fill Description
  await page
    .getByLabel(/website description/i)
    .fill("This is a test website generated by Playwright");

  // Fill Email (required OR phone)
  await page.getByLabel(/email address/i).fill("test@example.com");

  // Optional: skip phone, social links

  // Next step
  await page.getByRole("button", { name: /next step/i }).click();

  // ✅ Step 4 reached
  await expect(
    page.getByRole("heading", { name: /finalize structure/i }),
  ).toBeVisible();
});
