// src/tests/wizard/step-4-complete.spec.ts
import { test, expect } from "@playwright/test";
import { login, goToWizard, completeStepOne } from "../helpers/wizard";

test("wizard step 4: user completes setup and redirects to preview after generation", async ({
  page,
}) => {
  test.setTimeout(180_000);

  await login(page);
  await goToWizard(page);
  await completeStepOne(page);

  // Step 2 -> Step 3
  const projectsPage = page.getByRole("button", { name: /projects/i });

  if (await projectsPage.isVisible()) {
    await projectsPage.click();
  }

  await page.getByRole("button", { name: /next step/i }).click();

  // Step 3
  await expect(
    page.getByRole("heading", { name: /website details/i }),
  ).toBeVisible();

  await page
    .getByLabel(/website name/i)
    .fill(`Playwright Test Website ${Date.now()}`);

  await page
    .getByLabel(/website description/i)
    .fill(
      "This is a real development E2E test website generated by Playwright.",
    );

  await page.getByLabel(/email address/i).fill("test@example.com");

  await page.getByRole("button", { name: /next step/i }).click();

  // Step 4
  await expect(
    page.getByRole("heading", { name: /finalize structure/i }),
  ).toBeVisible();
  await page.getByRole("button", { name: /complete setup/i }).click();

  await expect(
    page.getByRole("button", { name: /generating site/i }),
  ).toBeVisible({ timeout: 10_000 });

  await expect(
    page.getByRole("heading", { name: /generating your website/i }),
  ).toBeVisible({ timeout: 60_000 });

  await expect(page).toHaveURL(/\/preview\/[^/]+\?firstLoad=true/, {
    timeout: 180_000,
  });
});
