"use client";

import { useState } from "react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
} from "@/components/ui/select";
import { useStepFourLogic } from "../hooks/useStepFourLogic";
import { SectionType, sectionTypes } from "../types/section";
import { cn } from "@/lib/utils";
import { Plus, Lock } from "lucide-react";

export function StepFour() {
  const {
    selectedPages,
    activeTab,
    setActiveTab,
    getCurrentPageContent,
    handleAddSection,
  } = useStepFourLogic();

  const [selectedSection, setSelectedSection] = useState("");

  if (selectedPages.length === 0) return null;

  const currentPageContent = getCurrentPageContent();
  const isHomePage = activeTab === "home";

  return (
    <div className="max-w-xl mx-auto space-y-12">
      {/* 1. Simple Header */}
      <div className="text-center space-y-2">
        <h2 className="text-2xl font-semibold tracking-tight">
          Page Structure
        </h2>
        <p className="text-muted-foreground text-sm">
          Arrange the sections for your website. AI handles the content.
        </p>
      </div>

      {/* 2. Navigation */}
      <div className="flex justify-center border-b">
        {selectedPages.map((page) => (
          <button
            key={page}
            onClick={() => setActiveTab(page)}
            className={cn(
              "px-6 py-3 text-sm font-medium capitalize transition-all border-b-2 -mb-[2px]",
              activeTab === page
                ? "border-primary text-primary"
                : "border-transparent text-muted-foreground hover:text-foreground",
            )}
          >
            {page}
          </button>
        ))}
      </div>

      {/* 3. The Section List with Descriptions */}
      <div className="space-y-3">
        {currentPageContent.sections.map((section) => {
          const isHero = section.type === "hero";
          const typeInfo = sectionTypes.find((t) => t.value === section.type);

          return (
            <div
              key={section.id}
              className="flex items-center justify-between p-4 bg-card border rounded-lg transition-colors hover:border-muted-foreground/20"
            >
              <div className="space-y-0.5">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-semibold capitalize">
                    {section.type.replace("-", " ")}
                  </span>
                  {/* Keep the badge only for the Hero to show it's the anchor */}
                  {isHero && (
                    <span className="inline-flex items-center gap-1 text-[9px] uppercase tracking-tighter font-bold text-muted-foreground bg-muted px-1.5 py-0.5 rounded">
                      <Lock className="w-2.5 h-2.5" /> Fixed
                    </span>
                  )}
                </div>
                <p className="text-xs text-muted-foreground">
                  {typeInfo?.description || "Content will be generated by AI."}
                </p>
              </div>

              {/* The delete button is gone. Total simplicity. */}
            </div>
          );
        })}

        {/* 4. Minimalist Add Button */}
        {isHomePage && (
          <div className="pt-2">
            <Select
              value={selectedSection}
              onValueChange={(value: string) => {
                handleAddSection(value as SectionType);
                setSelectedSection("");
              }}
            >
              <SelectTrigger className="w-full h-12 bg-transparent border-dashed border-2 hover:bg-muted/30 transition-all">
                <div className="flex items-center justify-center gap-2 text-muted-foreground text-sm font-medium">
                  <Plus className="w-4 h-4" />
                  <span>Add Section</span>
                </div>
              </SelectTrigger>
              <SelectContent>
                {sectionTypes
                  .filter((t) => t.value !== "hero")
                  .map((type) => (
                    <SelectItem key={type.value} value={type.value}>
                      <div className="flex flex-col py-0.5">
                        <span className="font-medium text-sm">
                          {type.label}
                        </span>
                        <span className="text-[10px] text-muted-foreground leading-tight">
                          {type.description}
                        </span>
                      </div>
                    </SelectItem>
                  ))}
              </SelectContent>
            </Select>
          </div>
        )}
      </div>
    </div>
  );
}
