"use client";

import type React from "react";

import { useState, useRef, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Send, Sparkles, User, X } from "lucide-react";
import { cn } from "@/lib/utils";
import type { WebElement } from "@/features/preview/types/webElement";

interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: Date;
}

interface ChatPanelJsonProps {
  onClose?: () => void;
  onWebsiteGenerated: (elements: WebElement[]) => void;
}

export function ChatPanelJson({
  onClose,
  onWebsiteGenerated,
}: ChatPanelJsonProps) {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "1",
      role: "assistant",
      content:
        "Hello! I'm sencill AI. Tell me about the website you'd like to create. What type of business is it for?",
      timestamp: new Date(),
    },
  ]);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: "user",
      content: input,
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInput("");
    setIsLoading(true);

    setTimeout(() => {
      const aiMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content:
          "Great! I'm generating your website now. You'll see the preview update on the right side.",
        timestamp: new Date(),
      };
      setMessages((prev) => [...prev, aiMessage]);

      // Generate sample website JSON based on user input
      const sampleWebsite: WebElement[] = [
        {
          id: 1,
          tag: "div",
          class:
            "min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 p-8",
          children: [
            {
              id: 2,
              tag: "header",
              class: "bg-white rounded-lg shadow-lg p-6 mb-8",
              children: [
                {
                  id: 3,
                  tag: "h1",
                  class: "text-4xl font-bold text-gray-900 mb-2",
                  content: "Welcome to Your New Website",
                },
                {
                  id: 4,
                  tag: "p",
                  class: "text-lg text-gray-600",
                  content: "Generated by sencill AI based on your description",
                },
              ],
            },
            {
              id: 5,
              tag: "main",
              class: "bg-white rounded-lg shadow-lg p-8 mb-8",
              children: [
                {
                  id: 6,
                  tag: "h2",
                  class: "text-2xl font-semibold text-gray-800 mb-4",
                  content: "About Us",
                },
                {
                  id: 7,
                  tag: "p",
                  class: "text-gray-700 mb-4 leading-relaxed",
                  content:
                    "This is a sample website generated based on your request. The AI has created a beautiful, responsive layout that you can customize further.",
                },
                {
                  id: 8,
                  tag: "div",
                  class: "grid grid-cols-1 md:grid-cols-3 gap-6 mt-8",
                  children: [
                    {
                      id: 9,
                      tag: "div",
                      class: "bg-blue-50 p-6 rounded-lg",
                      children: [
                        {
                          id: 10,
                          tag: "h3",
                          class: "text-xl font-semibold text-blue-900 mb-2",
                          content: "Feature 1",
                        },
                        {
                          id: 11,
                          tag: "p",
                          class: "text-blue-700",
                          content: "Amazing feature description goes here",
                        },
                      ],
                    },
                    {
                      id: 12,
                      tag: "div",
                      class: "bg-indigo-50 p-6 rounded-lg",
                      children: [
                        {
                          id: 13,
                          tag: "h3",
                          class: "text-xl font-semibold text-indigo-900 mb-2",
                          content: "Feature 2",
                        },
                        {
                          id: 14,
                          tag: "p",
                          class: "text-indigo-700",
                          content: "Another great feature description",
                        },
                      ],
                    },
                    {
                      id: 15,
                      tag: "div",
                      class: "bg-purple-50 p-6 rounded-lg",
                      children: [
                        {
                          id: 16,
                          tag: "h3",
                          class: "text-xl font-semibold text-purple-900 mb-2",
                          content: "Feature 3",
                        },
                        {
                          id: 17,
                          tag: "p",
                          class: "text-purple-700",
                          content: "One more awesome feature",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              id: 18,
              tag: "footer",
              class:
                "bg-gray-800 text-white rounded-lg shadow-lg p-6 text-center",
              children: [
                {
                  id: 19,
                  tag: "p",
                  class: "text-sm",
                  content: "© 2025 Your Business. Generated by sencill AI.",
                },
              ],
            },
          ],
        },
      ];

      onWebsiteGenerated(sampleWebsite);
      setIsLoading(false);
    }, 2000);
  };

  return (
    <div className="flex h-full flex-col bg-background">
      <div className="border-b border-border bg-card px-6 py-4">
        <div className="flex items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/20">
              <Sparkles className="h-5 w-5 text-primary" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-foreground">
                sencill AI
              </h2>
              <p className="text-sm text-muted-foreground">Website Generator</p>
            </div>
          </div>
          {onClose && (
            <Button
              variant="ghost"
              size="icon"
              onClick={onClose}
              className="h-8 w-8 text-muted-foreground hover:text-foreground"
            >
              <X className="h-5 w-5" />
            </Button>
          )}
        </div>
      </div>

      <ScrollArea className="flex-1 px-6 py-4">
        <div ref={scrollRef} className="space-y-4">
          {messages.map((message) => (
            <div
              key={message.id}
              className={cn(
                "flex gap-3",
                message.role === "user" ? "justify-end" : "justify-start",
              )}
            >
              {message.role === "assistant" && (
                <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-primary/20">
                  <Sparkles className="h-4 w-4 text-primary" />
                </div>
              )}
              <div
                className={cn(
                  "max-w-[80%] rounded-lg px-4 py-3",
                  message.role === "user"
                    ? "bg-secondary text-secondary-foreground"
                    : "bg-card border border-border text-foreground",
                )}
              >
                <p className="text-sm leading-relaxed">{message.content}</p>
                <span className="mt-1 block text-xs opacity-60">
                  {message.timestamp.toLocaleTimeString([], {
                    hour: "2-digit",
                    minute: "2-digit",
                  })}
                </span>
              </div>
              {message.role === "user" && (
                <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-secondary/20">
                  <User className="h-4 w-4 text-secondary" />
                </div>
              )}
            </div>
          ))}
          {isLoading && (
            <div className="flex gap-3">
              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-primary/20">
                <Sparkles className="h-4 w-4 text-primary animate-pulse" />
              </div>
              <div className="rounded-lg border border-border bg-card px-4 py-3">
                <div className="flex gap-1">
                  <div className="h-2 w-2 animate-bounce rounded-full bg-primary [animation-delay:-0.3s]"></div>
                  <div className="h-2 w-2 animate-bounce rounded-full bg-primary [animation-delay:-0.15s]"></div>
                  <div className="h-2 w-2 animate-bounce rounded-full bg-primary"></div>
                </div>
              </div>
            </div>
          )}
        </div>
      </ScrollArea>

      <div className="border-t border-border bg-card px-6 py-4">
        <form onSubmit={handleSubmit} className="flex gap-2">
          <Textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Describe your website... (e.g., 'Create a travel agency website with a hero section')"
            className="min-h-[60px] max-h-[120px] resize-none"
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                handleSubmit(e);
              }
            }}
            disabled={isLoading}
          />
          <Button
            type="submit"
            size="icon"
            className="h-[60px] w-[60px] shrink-0 bg-primary text-primary-foreground hover:bg-primary/90"
            disabled={isLoading || !input.trim()}
          >
            <Send className="h-5 w-5" />
          </Button>
        </form>
        <p className="mt-2 text-xs text-muted-foreground">
          Press Enter to send, Shift+Enter for new line
        </p>
      </div>
    </div>
  );
}
